
// This file has been generated by the GUI designer. Do not modify.
namespace EssentialsAddin
{
	public partial class OutputFilterWidget
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label filterLabel;

		private global::Gtk.Entry filterEntry;

		private global::Gtk.Button updateButton;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget EssentialsAddin.OutputFilterWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = -1;
			this.HeightRequest = -1;
			this.Sensitive = true;
			this.CanDefault = false;
			this.CanFocus = false;
			this.ExtensionEvents = ((global::Gdk.ExtensionMode)(0));
			this.Name = "EssentialsAddin.OutputFilterWidget";
			// Container child EssentialsAddin.OutputFilterWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.WidthRequest = -1;
			this.vbox1.HeightRequest = -1;
			this.vbox1.Sensitive = true;
			this.vbox1.CanDefault = false;
			this.vbox1.CanFocus = false;
			this.vbox1.ExtensionEvents = ((global::Gdk.ExtensionMode)(0));
			this.vbox1.Name = "vbox1";
			this.vbox1.Homogeneous = false;
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(0));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.WidthRequest = -1;
			this.hbox1.HeightRequest = -1;
			this.hbox1.Sensitive = true;
			this.hbox1.CanDefault = false;
			this.hbox1.CanFocus = false;
			this.hbox1.ExtensionEvents = ((global::Gdk.ExtensionMode)(0));
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = false;
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(0));
			// Container child hbox1.Gtk.Box+BoxChild
			this.filterLabel = new global::Gtk.Label();
			this.filterLabel.WidthRequest = -1;
			this.filterLabel.HeightRequest = -1;
			this.filterLabel.Sensitive = true;
			this.filterLabel.CanDefault = false;
			this.filterLabel.CanFocus = false;
			this.filterLabel.ExtensionEvents = ((global::Gdk.ExtensionMode)(0));
			this.filterLabel.Name = "filterLabel";
			this.filterLabel.Xpad = 10;
			this.filterLabel.Ypad = 0;
			this.filterLabel.Xalign = 0.5F;
			this.filterLabel.Yalign = 0.5F;
			this.filterLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Filter");
			this.filterLabel.UseMarkup = false;
			this.filterLabel.UseUnderline = false;
			this.filterLabel.Wrap = false;
			this.filterLabel.Justify = ((global::Gtk.Justification)(0));
			this.filterLabel.Selectable = false;
			this.filterLabel.Ellipsize = ((global::Pango.EllipsizeMode)(0));
			this.filterLabel.WidthChars = -1;
			this.filterLabel.MaxWidthChars = -1;
			this.filterLabel.SingleLineMode = false;
			this.filterLabel.Angle = 0D;
			this.hbox1.Add(this.filterLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.filterLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(2));
			// Container child hbox1.Gtk.Box+BoxChild
			this.filterEntry = new global::Gtk.Entry();
			this.filterEntry.TooltipMarkup = "Seperate by space, colon or semicolon";
			this.filterEntry.WidthRequest = -1;
			this.filterEntry.HeightRequest = -1;
			this.filterEntry.Sensitive = true;
			this.filterEntry.CanDefault = false;
			this.filterEntry.CanFocus = true;
			this.filterEntry.ExtensionEvents = ((global::Gdk.ExtensionMode)(0));
			this.filterEntry.Name = "filterEntry";
			this.filterEntry.Text = "";
			this.filterEntry.IsEditable = true;
			this.filterEntry.WidthChars = -1;
			this.filterEntry.MaxLength = 0;
			this.filterEntry.HasFrame = true;
			this.filterEntry.ActivatesDefault = false;
			this.filterEntry.Visibility = true;
			this.filterEntry.InvisibleChar = '●';
			this.filterEntry.Xalign = 0F;
			this.hbox1.Add(this.filterEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.filterEntry]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.updateButton = new global::Gtk.Button();
			this.updateButton.WidthRequest = -1;
			this.updateButton.HeightRequest = -1;
			this.updateButton.Sensitive = true;
			this.updateButton.CanDefault = false;
			this.updateButton.CanFocus = true;
			this.updateButton.ExtensionEvents = ((global::Gdk.ExtensionMode)(0));
			this.updateButton.Name = "updateButton";
			this.updateButton.UseStock = false;
			this.updateButton.UseUnderline = true;
			this.updateButton.FocusOnClick = true;
			this.updateButton.Relief = ((global::Gtk.ReliefStyle)(1));
			this.updateButton.Xalign = 0.5F;
			this.updateButton.Yalign = 0.5F;
			this.updateButton.BorderWidth = ((uint)(0));
			this.updateButton.Label = global::Mono.Unix.Catalog.GetString("Update");
			this.hbox1.Add(this.updateButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.updateButton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(2));
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = -1;
			this.GtkScrolledWindow.HeightRequest = -1;
			this.GtkScrolledWindow.Sensitive = true;
			this.GtkScrolledWindow.CanDefault = false;
			this.GtkScrolledWindow.CanFocus = false;
			this.GtkScrolledWindow.ExtensionEvents = ((global::Gdk.ExtensionMode)(0));
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.WindowPlacement = ((global::Gtk.CornerType)(0));
			this.GtkScrolledWindow.BorderWidth = ((uint)(0));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.WidthRequest = -1;
			this.textview1.HeightRequest = -1;
			this.textview1.Sensitive = true;
			this.textview1.CanDefault = false;
			this.textview1.CanFocus = true;
			this.textview1.ExtensionEvents = ((global::Gdk.ExtensionMode)(0));
			this.textview1.Name = "textview1";
			this.textview1.Editable = true;
			this.textview1.CursorVisible = true;
			this.textview1.Overwrite = false;
			this.textview1.AcceptsTab = true;
			this.textview1.Justification = ((global::Gtk.Justification)(0));
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(0));
			this.textview1.PixelsAboveLines = 0;
			this.textview1.PixelsBelowLines = 0;
			this.textview1.PixelsInsideWrap = 0;
			this.textview1.LeftMargin = 10;
			this.textview1.RightMargin = 0;
			this.textview1.Indent = 0;
			this.GtkScrolledWindow.Add(this.textview1);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w6.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.filterLabel.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.FilterLabel_ButtonPress);
			this.filterEntry.Changed += new global::System.EventHandler(this.FilterEntry_Changed);
			this.updateButton.Clicked += new global::System.EventHandler(this.UpdateButton_Clicked);
		}
	}
}
