
// This file has been generated by the GUI designer. Do not modify.
namespace EssentialsAddin
{
	public partial class SolutionFilterWidget
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Label filterLabel;

		private global::Gtk.Entry filterEntry;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget EssentialsAddin.SolutionFilterWidget
			global::Stetic.BinContainer.Attach(this);
			this.HeightRequest = 25;
			this.CanFocus = true;
			this.Name = "EssentialsAddin.SolutionFilterWidget";
			// Container child EssentialsAddin.SolutionFilterWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.filterLabel = new global::Gtk.Label();
			this.filterLabel.Name = "filterLabel";
			this.filterLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Filter:");
			this.hbox1.Add(this.filterLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.filterLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.filterEntry = new global::Gtk.Entry();
			this.filterEntry.CanFocus = true;
			this.filterEntry.Name = "filterEntry";
			this.filterEntry.IsEditable = true;
			this.filterEntry.InvisibleChar = '●';
			this.hbox1.Add(this.filterEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.filterEntry]));
			w2.Position = 1;
			w2.Padding = ((uint)(1));
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.filterEntry.Changed += new global::System.EventHandler(this.OnFilterEntryChanged);
		}
	}
}
