
// This file has been generated by the GUI designer. Do not modify.
namespace EssentialsAddin
{
	public partial class OutputFilterWidget
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label filterLabel;

		private global::Gtk.Entry filterEntry;

		private global::Gtk.Button updateButton;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget EssentialsAddin.OutputFilterWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "EssentialsAddin.OutputFilterWidget";
			// Container child EssentialsAddin.OutputFilterWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.filterLabel = new global::Gtk.Label();
			this.filterLabel.Name = "filterLabel";
			this.filterLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Filter");
			this.hbox1.Add(this.filterLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.filterLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(2));
			// Container child hbox1.Gtk.Box+BoxChild
			this.filterEntry = new global::Gtk.Entry();
			this.filterEntry.TooltipMarkup = "Seperate by space, colon or semicolon";
			this.filterEntry.CanFocus = true;
			this.filterEntry.Name = "filterEntry";
			this.filterEntry.IsEditable = true;
			this.filterEntry.InvisibleChar = '●';
			this.hbox1.Add(this.filterEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.filterEntry]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.updateButton = new global::Gtk.Button();
			this.updateButton.CanFocus = true;
			this.updateButton.Name = "updateButton";
			this.updateButton.UseUnderline = true;
			this.updateButton.Relief = ((global::Gtk.ReliefStyle)(1));
			this.updateButton.Label = global::Mono.Unix.Catalog.GetString("Update");
			this.hbox1.Add(this.updateButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.updateButton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(2));
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add(this.textview1);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w6.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.filterLabel.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.FilterLabel_ButtonPress);
			this.filterEntry.Changed += new global::System.EventHandler(this.FilterEntry_Changed);
			this.updateButton.Clicked += new global::System.EventHandler(this.UpdateButton_Clicked);
		}
	}
}
